config/routes.rb
Rails.application.routes.draw do
  resources :reports
  resources :notifications
  get 'task_followers/create'
  post 'notifications/new_feeds', as: "new_feeds"
  post 'notifications/set_notifications', as: "set_notifications"
  resources :blogs

  post 'tasks/sort'
  resources :activities
  resources :teams do
    resources :projects
  end
  resources :projects do

    resources :tasks
    post 'tasks/:id/owner' => "tasks#owner", as: "task_owner"
    post 'tasks/:id/deadline' => "tasks#deadline", as: "task_deadline"
    post 'tasks/:id/completed' => "tasks#completed", as: "task_completed"
    resources :blogs
  end

  get 'tasks/user_team'

  delete 'projects/:id/' => "projects#destroy", as: "destroy_project"
  delete 'teams/:id' => "teams#destroy", as: "destroy_team"
  resources :tasks do
    resources :comments
    resources :task_followers
  end

  resources :homes
  devise_for :users, :controllers => {:registrations => 'users/registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'
  get 'dashboard' => "dashboards#index"
  get 'search' => "tasks#search"

  resources :teams do
    resources 'memberships'
    post 'memberships/create', as: 'add_member'
    delete 'memberships/destroy', as: 'delete_member'
  end

  get 'switch' => "teams#switch"
end

app/models/task.rb
class Task < ApplicationRecord

  default_scope { order("position ASC") }

  belongs_to :project
  belongs_to :user, optional: true
  belongs_to :owner, class_name: 'User'
  has_many :task_followers, dependent: :destroy
  has_many :followers, :through => :task_followers, :source => :user
  has_many :comments, dependent: :destroy
  has_many :activities, as: :subject, dependent: :destroy
  has_one :project_news, class_name: 'Activity', as: :trackable, dependent: :destroy

  validates :name, presence: true

  def isCompleted?
    !!completed_at
  end

  def followers
    @followers = []
    @task_followers = TaskFollower.where(task_id: id)
    @task_followers.each do |task_follower|
      @followers << task_follower.user
    end
    @followers
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :load_project, only: [:edit, :create, :show, :completed, :update, :destroy]
  def new
    @project = Project.find(params[:project_id])
    @task = Task.new
  end

  def sort
    params[:postition].each do |key, value|
      Task.find(value[:id]).update_attribute(:position, value[:position])
    end

    render :nothing => true
  end

  def edit
    @task = Task.find(params[:id])
  end

  def index
    if params[:q]
      @tasks = @search.result
    elsif current_user
      @tasks = current_user.tasks.order('position')
    end
  end

  def create

    @task = @project.tasks.build task_params
    @task.owner = current_user

    if @task.save
      track_activity current_user, @project, @task

      @project.reload
      respond_to do |format|
        format.html { redirect_to @project }
        format.json { render json: @project }

        #NOTE: adding format.js shows an uneccessary modal
        #format.js
      end
    else
      flash[:error] = "#{ @project.errors.full_messages.to_sentence }"
      redirect_to teams_path
    end
  end

  def user_team
    if current_team
      @users = current_team.team_member
    end

    respond_to do |format|
      format.json {render json: @users}
    end

  end
  def show
    @task = Task.find params[:id]

    respond_to do |format|

      format.html {redirect_to @project}
      if params[:redirect] == "true"
        flash[:task] = @task.id
      else
        format.js
      end
    end
  end

  def completed
    @task = Task.find params[:id]
    if params[:completed] == "true"
      @task.completed_at = Time.zone.now
      @task.save
      track_activity current_user, @task, nil, 'completed'
    elsif params[:completed] == "false"
      @task.completed_at = nil
      Activity.where(subject: @task, action: 'completed').each {|a| a.destroy!}
      @task.save
    end

    respond_to do |format|
      format.js
#      format.html {redirect_to project_path(@project)}
    end
  end

  def owner
    load_project
    @task = Task.find params[:id]
    if params[:owner_id]
      @owner = User.find params[:owner_id]
      @task.owner_id = params[:owner_id]
      @task.save
      track_activity current_user, @task, @owner, 'assign'
    end

    respond_to do |format|
#      format.html {redirect_to project_path(@project)}
      format.js
    end
  end


  def deadline
    load_project
    @task = Task.find params[:id]
    if params[:due_date]
      @task.due_date = params[:due_date]
      #binding.pry
      if @task.save
        flash[:success] = "Change deadline successfully"
      else
        flash[:error] = "Change deadline failed"
      end
    end

    respond_to do |format|
      #format.html {redirect_to project_path(@project)}
      format.js
    end
  end

  def update

  end

  def destroy
    @task = Task.find params[:id]
    @task.destroy
    redirect_back fallback_location: project_path(@project)
  end
  private
  def task_params
    params.require(:task).permit(:task_id, :name, :description, :position)
  end

  def load_project
    @project = Project.find params[:project_id]
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_followers.html.erb
<% task.task_followers.each do |task_follower| %>
  <%= div_for task_follower do %>
    <%= render task_follower %>
  <% end %>
<% end %>

app/views/tasks/_form.html.erb
<%= form_for([@project, @task], remote: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control', placeholder: 'What is the Task?'%>
  <%= f.label :description %>
  <%= f.text_area :description, class: 'form-control', rows: 3, placeholder: 'Task Description' %>

  <hr>
  <%= f.submit 'Add', class: 'btn btn-primary'%>
<% end %>

app/views/tasks/_task.html.erb
<h4><strong><%= task.name %></strong>  <div class="btn-group pull-right">
  <button class="btn btn-secondary btn-sm dropdown-toggle btn-sm rounded-s" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <i class="fa fa-ellipsis-h" aria-hidden="true"></i>
  </button>
  <div class="dropdown-menu dropdown-menu-right">
    <%= link_to " Edit", edit_project_task_path(@project, task), class: "dropdown-item btn btn-secondary btn-sm rounded-s"%>
    <%= link_to " Delete", project_task_path(@project, task), :method => :delete, class: "dropdown-item btn-sm rounded-s"%>
  </div>
</div>
</h4>
    <div id="remote">
      <i class="fa fa-user fa-lg"></i>&nbsp;&nbsp;<input class="typeahead form-control underlined" id="owner_select"  size="<%= task.owner.name.length if task.owner %>" type="text" placeholder="Type to find team members" value="<%= task.owner.name if task.owner %>" style="font-size:15px;">
    </div>
    <div>
      <i class="fa fa-calendar fa-lg"></i>&nbsp;<input type="text" class="datepicker tt-hint form-control underlined" size="10"  data-request-url="<%= project_task_deadline_path(task.project, task)%>" onchange="handleDueDateChange(this)" value="<%= task.due_date.to_date.to_s if task.due_date%>" style="font-size:15px; display:inline; color:black; width:14%;">
    </div>
  <br>
    <% if task.description %>
    <tab><%= markdown(task.description) %></tab>
    <% end %>
  <div class="comments-wrapper">
    <div class="comments">
      <%= render "tasks/task_comments", comments: task.comments %>
    </div>

    <%= form_for [task, Comment.new], remote: true do |f| %>
      <div class="form-group">
        <%= f.text_field :content, placeholder: "Comment", autocomplete: 'off', rows: 5, class: "form-control underlined" %><br />
      </div>
    <% end %>

    <div class="followers" style="display:inline">
      <h6>Followers:</h6>
      <%= render "tasks/followers", task: task %>
    </div>
    <% if current_team %>
      <div id="remote" style="display:inline">
        <input class="typeahead form-control underlined" id="follower_select" type="text" size="10" placeholder="Add followers" style="padding:10px; font-size: 15px;">
      </div>
    <% end %>
  </div>
<br>

<!-- old "Mark as Completed feature set. Don't need to use this anymore. " -->
  <!-- <div class="form-check">
    <label class="form-check-label">
      <input id="task_completed" data-request-url=<%=project_task_completed_path(task.project, task)%> onchange="handleChange(this);" class="form-check-input" type="checkbox" <%="checked" if task.isCompleted? %>>
      Mark as completed
    </label>
  </div> -->
<script>

var bestPictures = new Bloodhound({
  datumTokenizer: Bloodhound.tokenizers.obj.whitespace("name"),
  queryTokenizer: Bloodhound.tokenizers.whitespace,
  prefetch:
  {
    url: '/tasks/user_team.json'
  }
});

$(".datepicker").datepicker({dateFormat: 'dd-mm-yy'});


$('#remote .typeahead').typeahead(null, {
  name: 'best-pictures',
  display: 'name',
  source: bestPictures
});

$('#owner_select').bind('typeahead:select', function(ev, suggestion) {
  console.log('Selection: ' + suggestion.email);

  url = '<%= project_task_owner_path(task.project, task)%>' + '.js';
  console.log('Post to url: ' + url);
  $.post(url, {
    owner_id: suggestion.id,
    project_id: <%= task.project.id %>,
    task_id: <%= task.id %>
}
);
  });
$('#follower_select').bind('typeahead:select', function(ev, suggestion) {
  console.log('Follower Selection: ' + suggestion.email);

  url = '<%= task_task_followers_path(task, TaskFollower.new)%>' + '.js';
  console.log('Post to url: ' + url);
  $.post(url, {
    user_id: suggestion.id,
    task_id: <%= task.id %>
}
);
  });
$('.chosen-select').chosen();
</script>

app/views/tasks/_task_comments.html.erb
<% comments.each do |comment| %>
  <%= div_for comment do %>
    <%= render comment %>
  <% end %>
<% end %>

app/views/tasks/_task_item.html.erb
<li class="item item-task" data-id="<%= task.id %>">
  <div class="item-row">
    <div class="item-col fixed item-col-check"> <label class="item-check" id="<%="completed-icon-#{task.id}"%>">
        <%= task_completed_icon(task) %><span></span>
      </label> </div>
      <div class="item-col fixed item-col-stats">
        <% if task.owner %>
          <%= image_tag(task.owner.avatar, class: "round-image-16",:align=> "middle") %>
        <% end %>
      </div>
      <div class="item-col fixed pull-left item-col-title">
        <div class="item-heading">Name</div>
        <div>
          <a href="item-editor.html" class="">
            <% if task.isCompleted? %>
              <h4 class="item-title"><s><%= link_to task.name, project_task_path(task.project, task), remote:true%></h4></s> </a>
        <% else %>
          <h4 class="item-title"><%= link_to task.name, project_task_path(task.project, task), remote:true%></h4> </a>
      <% end %>
        </div>
      </div>
      <div class="item-col item-col-date">
        <div class="item-heading">Due Date</div>
        <div class="no-overflow" id="<%="due-date-#{task.id}"%>"><%= deadline_warning(task) %></div>
      </div>
  </div>
</li>

app/views/tasks/_tasks.html.erb
<article class="content items-list-page">
    <div class="card items">
        <ul class="item-list"  id="tasks_list">
            <li class="item item-list-header hidden-sm-down">
                <div class="item-row" style="border-bottom:0.5px solid #d7dde4;">
                    <div class="item-col fixed item-col-check"></div>
                    <div class="item-col item-col-header fixed item-col-stats">
                        <div> <span>Owner</span> </div>
                    </div>
                    <div class="item-col item-col-header item-col-title">
                        <div> <span>Name</span> </div>
                    </div>
                    <div class="item-col item-col-header item-col-date">
                        <div> <span>Due Date</span> </div>
                    </div>
                </div>
            </li>
            <% tasks.each do |task| %>
            <li class="item item-task" data-id="<%= task.id %>">
                <div class="item-row" >
                  <% if task.name.last == ":" %>
                    <div class="item-col" style="border-bottom:0.5px solid #d7dde4;">
                      <h4><strong><%= link_to task.name, project_task_path(task.project, task), remote:true, class: 'header-task'%></strong></h4>
                    </div>
                  <% else %>
                    <div class="item-col fixed item-col-check">                         <div class="form-check">
                                              <label class="form-check-label">
                                                <input id="task_completed" data-request-url=<%=project_task_completed_path(task.project, task)%> onchange="handleChange(this);" class="form-check-input" type="checkbox" <%="checked" if task.isCompleted? %>>
                                              </label>
                                            </div>
</label> </div>
                    <div class="item-col fixed item-col-stats">
                          <% if task.owner %>
                            <%= image_tag(task.owner.avatar, class: "round-image-16",:align=> "middle") %>
                          <% end %>
                    </div>
                    <div class="item-col fixed pull-left item-col-title">
                        <!-- <div class="item-heading">Name</div> -->
                        <div>
                            <a href="item-editor.html" class="">
                              <% if task.isCompleted? %>
                                <h4 class="item-title"><s><%= link_to task.name, project_task_path(task.project, task), remote:true%></h4></s> </a>
                              <% else %>
                                <h4 class="item-title"><%= link_to task.name, project_task_path(task.project, task), remote:true%></h4> </a>
                              <% end %>
                        </div>
                    </div>
                    <div class="item-col item-col-date">
                        <!-- <div class="item-heading">Due Date</div> -->
                        <div class="no-overflow" id="<%="due-date-#{task.id}"%>" style="font-size:12px;"><%= deadline_warning(task) %></div>
                    </div>
                  <% end %>
                </div>
            </li>
              <!-- <%= render 'tasks/task_item', task: task%> -->
            <% end %>
        </ul>
    </div>
</article>

app/views/tasks/completed.js.erb
console.log("got completed updated");
$("<%="#completed-icon-#{@task.id}"%>").html("<%= task_completed_icon(@task) %>");

app/views/tasks/deadline.js.erb
console.log("got deadline updated")
$("<%="#due-date-#{@task.id}"%>").html("<%= deadline_warning(@task) %>");

app/views/tasks/index.html.erb
<h3><strong>Tasks</strong></h3>
<hr>
<div class="row placeholders">
  <div class="center-container col-md-6" >
    <% if @tasks.any? %>
      <%= render partial: "tasks", locals: {tasks: @tasks} %>
    <% else %>
      <p>No tasks found.</p>
      <% end %>
  </div>
  <div class="right-container col-md-6">
  </div>
</div>

app/views/tasks/move.js.erb
var row = $('*[data-role="task<%= @task.id%>"]');
var new_row_html = '<%= j render @tasks %>'

row.replaceWith(new_row_html);

app/views/tasks/new.html.erb
<h1>
  New task
</h1>
<%= render partial: 'form', locals: {project:@project, task: @task}%>

app/views/tasks/new.js.erb
$('#dialog h3').html("<i class='glyphicon glyphicon-plus'></i> New Task");

// Render the new form
$('.modal-body').html('<%= j render("tasks/form") %>');

// Show the dynamic dialog
$('#dialog').modal("show");

// Set focus to the first element
$('#dialog').on('shown.bs.modal', function () {
    $('.first_input').focus()
  })

app/views/tasks/search.html.erb
<div class="card col-sm-6 offset-sm-3">
  <div class="card-header">
    <h2>Search</h2>
  </div>
  <div class="card-block">
    <%= search_form_for @search do |f| %>
      <div class="form-group">
        <%= f.label :name_cont, "Name contains" %>
        <%= f.text_field :name_cont, :class=> "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :description_cont, "Description contains" %>
        <%= f.text_field :description_cont, :class=> "form-control" %>
      </div>
      <div class="actions"><%= f.submit "Search", :class=> "btn btn-primary" %></div>
    <% end %>
  </div>
</div>

app/views/tasks/show.js.erb
$(".right-container").html("<%= j render @task %>")