config/routes.rb
Rails.application.routes.draw do
  resources :reports
  resources :notifications
  get 'task_followers/create'
  post 'notifications/new_feeds', as: "new_feeds"
  post 'notifications/set_notifications', as: "set_notifications"
  resources :blogs

  post 'tasks/sort'
  resources :activities
  resources :teams do
    resources :projects
  end
  resources :projects do

    resources :tasks
    post 'tasks/:id/owner' => "tasks#owner", as: "task_owner"
    post 'tasks/:id/deadline' => "tasks#deadline", as: "task_deadline"
    post 'tasks/:id/completed' => "tasks#completed", as: "task_completed"
    resources :blogs
  end

  get 'tasks/user_team'

  delete 'projects/:id/' => "projects#destroy", as: "destroy_project"
  delete 'teams/:id' => "teams#destroy", as: "destroy_team"
  resources :tasks do
    resources :comments
    resources :task_followers
  end

  resources :homes
  devise_for :users, :controllers => {:registrations => 'users/registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'
  get 'dashboard' => "dashboards#index"
  get 'search' => "tasks#search"

  resources :teams do
    resources 'memberships'
    post 'memberships/create', as: 'add_member'
    delete 'memberships/destroy', as: 'delete_member'
  end

  get 'switch' => "teams#switch"
end

app/models/project.rb
class Project < ApplicationRecord
  validates :name, presence: true
  has_many :tasks, -> { order(position: :asc) }, dependent: :destroy
  belongs_to :team, optional: true
  has_many :blogs, dependent: :destroy
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:edit, :show, :update, :destroy]
  def index
    if current_team != nil
      @project = current_team.my_team_project
    end
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.create project_params
    @project.team = current_team
    respond_to do |format|
      if @project.save
        format.html { redirect_to projects_path }
        format.json { head :no_content }
        format.js
      else
        format.json { render json:@project.errors.full_messages,
                      status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

# TODO: fix positioning the task after adding it

  def show
    # NOTE: define params to show completed/not completed tasks
    if params[:completed] == "0"
      @tasks = @project.tasks.where("completed_at IS NULL").order('position desc')
    elsif params[:completed] == "1"
      @tasks = @project.tasks.where("completed_at IS NOT NULL").order('position desc')
    else
      @tasks = @project.tasks.order('position desc')
    end
  end

  def update
    respond_to do |format|
      if @project.update project_params
        format.json { head :no_content }
        format.js
      else
        format.json { render json: @project.errors.full_messages,
                      status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_path }
      format.json { head :no_content }
    end
  end

  private

  def set_project
    @project = Project.find params[:id]
  end

  def project_params
    params.require(:project).permit(:name, :current_team_id)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_dialog.html.erb
<div class="modal fade"
     id="dialog" tabindex="-1" role="dialog"
                               aria-labelledby="myModalLabel"
                               aria-hidden="true"
                               data-backdrop="static"
                               data-keyboard="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close"
                              data-dismiss="modal"
                              aria-label="Close">
          <span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title"></h3>
      </div>
      <div class="modal-body">
      </div>
      <div class="modal-footer">
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/projects/_form.html.erb
<%= form_for(@project, remote: true, html: { :role => "form"}) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control'%>
  <hr>
  <%= f.submit 'Create', class: 'btn btn-primary' %>
<% end %>

app/views/projects/_project.html.erb
<div class="container">
	<td><%= link_to project.name, project_path(project)%> </td>
	<td style="float:right; margin-right:20px;"><%= link_to 'Delete', destroy_project_path(project), method: :delete, class: 'btn btn-danger'%></td>
</div>

app/views/projects/create.js.erb
$('#dialog').modal('toggle');
$('.projects').append('<%= j render (@project) %>')

app/views/projects/destroy.js.erb
$('#project_<%= @project.id %>').fadeOut();

app/views/projects/index.html.erb
<div class="col-xl-12">
  <div class="row sameheight-container">
    <div class="card sameheight-item items">
      <div class="card-header bordered">
          <% if current_team %>
            <h3><strong><%= current_team.name %> Projects</strong></h3>
          <% end %>
            <div class="header-block pull-right">
              <%= link_to 'New Project', new_project_path, remote: true, data: { toggle: "modal", target: "#ajax-modal-project" },class: 'btn btn-primary'%>
            </div>
          </div>

          <div class="row placeholders">
            <div class="center-container">
              <table class="table">
                <tbody class="projects">
                  <% if current_team %>
                    <% current_team.projects.each do |project| %>
                    <tr id=<%=project.id%> >
                      <%= render 'project',project: project %>
                    </tr>
                    <% end %>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<h1>
	New project
</h1>

<%= render 'form' %>

app/views/projects/new.js.erb
$('#dialog h3').html("<i class='glyphicon glyphicon-plus'></i> New Project");

// Render the new form
$('.modal-body').html('<%= j render("projects/form") %>');

// Show the dynamic dialog
$('#dialog').modal("show");

// Set focus to the first element
$('#dialog').on('shown.bs.modal', function () {
		$('.first_input').focus()
	})

app/views/projects/show.html.erb
<div class="col-xl-12">
  <div class="row sameheight-container">
    <div class="card sameheight-item items col-sm-12">
      <div class="card-header bordered">
        <h3><strong> <%= @project.name %> &nbsp;</strong></h3>
          <%= link_to "Blog", project_blogs_path(@project), class: "btn btn-warning btn-sm rounded-s" %>
          <!-- View Selection -->
          <div class="btn-group">
            <button class="btn btn-secondary btn-sm dropdown-toggle btn-sm rounded-s" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fa fa-eye" aria-hidden="true"></i>
            </button>
            <div class="dropdown-menu">
              <%= link_to "All Tasks", project_path(@project), class: "dropdown-item btn btn-secondary btn-sm rounded-s"%>
              <%= link_to "Incomplete", "?completed=0", class: "dropdown-item btn btn-secondary btn-sm rounded-s"%>
              <%= link_to "Completed", "?completed=1", class: "dropdown-item btn btn-secondary btn-sm rounded-s"%>
            </div>
          <!-- End View Selection -->
          </div>
      </div>
      <div class="row placeholders">
        <div class="center-container col-md-6" id=<%= @project.id %> >
          <%= render partial: "tasks/tasks", locals: {tasks: @tasks} %>

          <%#= link_to 'New Task', new_project_task_path(@project), remote: true, data: { toggle: "modal", target: "#ajax-modal-project" },class: 'btn btn-primary btn-sm rounded-s'%>

          <%#= NOTE: you need label:false in the form below otherwise it won't work %>

          <%= form_for([@project, Task.new], remote: true) do |f| %>
            <%= f.text_field :name, class: 'form-control underlined', placeholder: 'New Task', label: false%>
          <% end %>

        </div>
        <div class="right-container col-md-6">
          <% if flash[:task]%>
            <%= render Task.find(flash[:task])%>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<%= render '/projects/dialog'%>